apiVersion: v1
kind: Secret
metadata:
  name: gangway
  namespace: tanzu-system-auth
type: Opaque
data:
  # openssl rand -base64 32 | pbcopy
  sesssionKey: yxJq1Lc19P52oxR163eKD/d7kb/vCwLs6oB+86Y4gw0=
  # clientSecret=$(openssl rand -base64 32)
  # echo -n "$clientSecret" | base64
  clientSecret: bWxWeFlTZ0I0TXgyTGg0enE3Qzg3TDJLOFVTZWt2eitTWTFiMXpuNURKWT0=

