apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: contour-selfsigned-ca-issuer
  namespace: tanzu-system-ingress
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: contour-ca
  namespace: tanzu-system-ingress
spec:
  secretName: contour-ca-key-pair
  duration: 8760h # 1year
  renewBefore: 360h # 15d
  organization:
  - "Project Contour"
  commonName: "Contour CA"
  isCA: true
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
  - contourca
  issuerRef:
    name: contour-selfsigned-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: contour-ca-issuer
  namespace: tanzu-system-ingress
spec:
  ca:
    secretName: contour-ca-key-pair
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: contour-cert
  namespace: tanzu-system-ingress
spec:
  secretName: contourcert
  duration: 8760h # 1year
  renewBefore: 360h # 15d
  organization:
  - "Project Contour"
  commonName: contour
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
  dnsNames:
  - contour
  - contour.tanzu-system-ingress
  - contour.tanzu-system-ingress.svc
  - contour.tanzu-system-ingress.svc.cluster.local
  issuerRef:
    name: contour-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: envoy-cert
  namespace: tanzu-system-ingress
spec:
  secretName: envoycert
  duration: 8760h # 1years
  renewBefore: 360h # 15d
  organization:
  - "Project Contour"
  commonName: envoy
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - client auth
  dnsNames:
  - envoy
  - envoy.tanzu-system-ingress
  - envoy.tanzu-system-ingress.svc
  - envoy.tanzu-system-ingress.svc.cluster.local
  issuerRef:
    name: contour-ca-issuer
    kind: Issuer
    group: cert-manager.io
